name: Test

on: 
  workflow_dispatch:
  # push:

jobs:
  job1:
    runs-on: ubuntu-20.04
    steps:  

    - name: build
        run: |
          mkdir -p data2
          mkdir -p cache
          echo asdf > data2/test.txt
          cd data2
          tar cfz  ../cache/test.tgz *
          cd ..

#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: tip
#          prerelease: true
#          files: 
#            cache/*.tgz

#    - name: test locale
#      run: |
#        locale -a
#        # sudo apt-get install -y locales
#        # locale -a
#        cd /usr/share/locales
#        sudo ./install-language-pack de_DE.UTF-8
#        locale -a
